<?php
/**
 * AuditTrailEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * AuditTrailEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description AuditTrailEntry
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AuditTrailEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "AuditTrailEntry"
     */
    public function testAuditTrailEntry()
    {

    }

    /**
     * Test attribute "text"
     */
    public function testPropertyText()
    {

    }

    /**
     * Test attribute "entered_date"
     */
    public function testPropertyEnteredDate()
    {

    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {

    }

    /**
     * Test attribute "audit_type"
     */
    public function testPropertyAuditType()
    {

    }

    /**
     * Test attribute "audit_sub_type"
     */
    public function testPropertyAuditSubType()
    {

    }

    /**
     * Test attribute "audit_source"
     */
    public function testPropertyAuditSource()
    {

    }

}
