<?php
/**
 * ConnectWiseHostedSetupTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * ConnectWiseHostedSetupTest Class Doc Comment
 *
 * @category    Class */
// * @description ConnectWiseHostedSetup
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConnectWiseHostedSetupTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ConnectWiseHostedSetup"
     */
    public function testConnectWiseHostedSetup()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "screen_id"
     */
    public function testPropertyScreenId()
    {

    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {

    }

    /**
     * Test attribute "url"
     */
    public function testPropertyUrl()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {

    }

    /**
     * Test attribute "pod_height"
     */
    public function testPropertyPodHeight()
    {

    }

    /**
     * Test attribute "toolbar_button_dialog_height"
     */
    public function testPropertyToolbarButtonDialogHeight()
    {

    }

    /**
     * Test attribute "toolbar_button_dialog_width"
     */
    public function testPropertyToolbarButtonDialogWidth()
    {

    }

    /**
     * Test attribute "toolbar_button_text"
     */
    public function testPropertyToolbarButtonText()
    {

    }

    /**
     * Test attribute "toolbar_button_tool_tip"
     */
    public function testPropertyToolbarButtonToolTip()
    {

    }

    /**
     * Test attribute "toolbar_button_icon_document_id"
     */
    public function testPropertyToolbarButtonIconDocumentId()
    {

    }

    /**
     * Test attribute "disabled_flag"
     */
    public function testPropertyDisabledFlag()
    {

    }

    /**
     * Test attribute "created_by"
     */
    public function testPropertyCreatedBy()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
