<?php
/**
 * DictionaryStringString_Test
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * DictionaryStringString_Test Class Doc Comment
 *
 * @category    Class */
// * @description DictionaryStringString_
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DictionaryStringString_Test extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DictionaryStringString_"
     */
    public function testDictionaryStringString_()
    {

    }

    /**
     * Test attribute "comparer"
     */
    public function testPropertyComparer()
    {

    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {

    }

    /**
     * Test attribute "keys"
     */
    public function testPropertyKeys()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_dictionary_t_key_t_value_keys"
     */
    public function testPropertySystemCollectionsGenericIDictionaryTKeyTValueKeys()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_read_only_dictionary_t_key_t_value_keys"
     */
    public function testPropertySystemCollectionsGenericIReadOnlyDictionaryTKeyTValueKeys()
    {

    }

    /**
     * Test attribute "values"
     */
    public function testPropertyValues()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_dictionary_t_key_t_value_values"
     */
    public function testPropertySystemCollectionsGenericIDictionaryTKeyTValueValues()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_read_only_dictionary_t_key_t_value_values"
     */
    public function testPropertySystemCollectionsGenericIReadOnlyDictionaryTKeyTValueValues()
    {

    }

    /**
     * Test attribute "this"
     */
    public function testPropertyThis()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_collection_system_collections_generic_key_value_pair_t_key_t_value_is_read_only"
     */
    public function testPropertySystemCollectionsGenericICollectionSystemCollectionsGenericKeyValuePairTKeyTValueIsReadOnly()
    {

    }

    /**
     * Test attribute "system_collections_i_collection_is_synchronized"
     */
    public function testPropertySystemCollectionsICollectionIsSynchronized()
    {

    }

    /**
     * Test attribute "system_collections_i_collection_sync_root"
     */
    public function testPropertySystemCollectionsICollectionSyncRoot()
    {

    }

    /**
     * Test attribute "system_collections_i_dictionary_is_fixed_size"
     */
    public function testPropertySystemCollectionsIDictionaryIsFixedSize()
    {

    }

    /**
     * Test attribute "system_collections_i_dictionary_is_read_only"
     */
    public function testPropertySystemCollectionsIDictionaryIsReadOnly()
    {

    }

    /**
     * Test attribute "system_collections_i_dictionary_keys"
     */
    public function testPropertySystemCollectionsIDictionaryKeys()
    {

    }

    /**
     * Test attribute "system_collections_i_dictionary_values"
     */
    public function testPropertySystemCollectionsIDictionaryValues()
    {

    }

    /**
     * Test attribute "system_collections_i_dictionary_item"
     */
    public function testPropertySystemCollectionsIDictionaryItem()
    {

    }

}
