<?php
/**
 * DocumentInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * DocumentInfoTest Class Doc Comment
 *
 * @category    Class */
// * @description DocumentInfo
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DocumentInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DocumentInfo"
     */
    public function testDocumentInfo()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "file_name"
     */
    public function testPropertyFileName()
    {

    }

    /**
     * Test attribute "server_file_name"
     */
    public function testPropertyServerFileName()
    {

    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {

    }

    /**
     * Test attribute "link_flag"
     */
    public function testPropertyLinkFlag()
    {

    }

    /**
     * Test attribute "image_flag"
     */
    public function testPropertyImageFlag()
    {

    }

    /**
     * Test attribute "public_flag"
     */
    public function testPropertyPublicFlag()
    {

    }

    /**
     * Test attribute "read_only_flag"
     */
    public function testPropertyReadOnlyFlag()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
