<?php
/**
 * KeyCollectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * KeyCollectionTest Class Doc Comment
 *
 * @category    Class */
// * @description KeyCollection
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KeyCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "KeyCollection"
     */
    public function testKeyCollection()
    {

    }

    /**
     * Test attribute "count"
     */
    public function testPropertyCount()
    {

    }

    /**
     * Test attribute "system_collections_generic_i_collection_t_key_is_read_only"
     */
    public function testPropertySystemCollectionsGenericICollectionTKeyIsReadOnly()
    {

    }

    /**
     * Test attribute "system_collections_i_collection_is_synchronized"
     */
    public function testPropertySystemCollectionsICollectionIsSynchronized()
    {

    }

    /**
     * Test attribute "system_collections_i_collection_sync_root"
     */
    public function testPropertySystemCollectionsICollectionSyncRoot()
    {

    }

}
