<?php
/**
 * MemberTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * MemberTest Class Doc Comment
 *
 * @category    Class */
// * @description Member
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MemberTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Member"
     */
    public function testMember()
    {

    }

    /**
     * Test attribute "admin_flag"
     */
    public function testPropertyAdminFlag()
    {

    }

    /**
     * Test attribute "allow_expenses_entered_against_companies_flag"
     */
    public function testPropertyAllowExpensesEnteredAgainstCompaniesFlag()
    {

    }

    /**
     * Test attribute "allow_in_cell_entry_on_time_sheet"
     */
    public function testPropertyAllowInCellEntryOnTimeSheet()
    {

    }

    /**
     * Test attribute "billable_forecast"
     */
    public function testPropertyBillableForecast()
    {

    }

    /**
     * Test attribute "calendar"
     */
    public function testPropertyCalendar()
    {

    }

    /**
     * Test attribute "calendar_sync_integration_flag"
     */
    public function testPropertyCalendarSyncIntegrationFlag()
    {

    }

    /**
     * Test attribute "country"
     */
    public function testPropertyCountry()
    {

    }

    /**
     * Test attribute "daily_capacity"
     */
    public function testPropertyDailyCapacity()
    {

    }

    /**
     * Test attribute "days_tolerance"
     */
    public function testPropertyDaysTolerance()
    {

    }

    /**
     * Test attribute "default_department_id"
     */
    public function testPropertyDefaultDepartmentId()
    {

    }

    /**
     * Test attribute "default_email"
     */
    public function testPropertyDefaultEmail()
    {

    }

    /**
     * Test attribute "default_location_id"
     */
    public function testPropertyDefaultLocationId()
    {

    }

    /**
     * Test attribute "default_phone"
     */
    public function testPropertyDefaultPhone()
    {

    }

    /**
     * Test attribute "disable_online_flag"
     */
    public function testPropertyDisableOnlineFlag()
    {

    }

    /**
     * Test attribute "enable_ldap_authentication_flag"
     */
    public function testPropertyEnableLdapAuthenticationFlag()
    {

    }

    /**
     * Test attribute "enable_mobile_flag"
     */
    public function testPropertyEnableMobileFlag()
    {

    }

    /**
     * Test attribute "enable_mobile_gps_flag"
     */
    public function testPropertyEnableMobileGpsFlag()
    {

    }

    /**
     * Test attribute "enter_time_against_company_flag"
     */
    public function testPropertyEnterTimeAgainstCompanyFlag()
    {

    }

    /**
     * Test attribute "expense_approver"
     */
    public function testPropertyExpenseApprover()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "hide_member_in_dispatch_portal_flag"
     */
    public function testPropertyHideMemberInDispatchPortalFlag()
    {

    }

    /**
     * Test attribute "hire_date"
     */
    public function testPropertyHireDate()
    {

    }

    /**
     * Test attribute "home_email"
     */
    public function testPropertyHomeEmail()
    {

    }

    /**
     * Test attribute "home_extension"
     */
    public function testPropertyHomeExtension()
    {

    }

    /**
     * Test attribute "home_phone"
     */
    public function testPropertyHomePhone()
    {

    }

    /**
     * Test attribute "hourly_cost"
     */
    public function testPropertyHourlyCost()
    {

    }

    /**
     * Test attribute "hourly_rate"
     */
    public function testPropertyHourlyRate()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "identifier"
     */
    public function testPropertyIdentifier()
    {

    }

    /**
     * Test attribute "inactive_date"
     */
    public function testPropertyInactiveDate()
    {

    }

    /**
     * Test attribute "inactive_flag"
     */
    public function testPropertyInactiveFlag()
    {

    }

    /**
     * Test attribute "include_in_utilization_reporting_flag"
     */
    public function testPropertyIncludeInUtilizationReportingFlag()
    {

    }

    /**
     * Test attribute "last_login"
     */
    public function testPropertyLastLogin()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "license_class"
     */
    public function testPropertyLicenseClass()
    {

    }

    /**
     * Test attribute "mapi_name"
     */
    public function testPropertyMapiName()
    {

    }

    /**
     * Test attribute "middle_initial"
     */
    public function testPropertyMiddleInitial()
    {

    }

    /**
     * Test attribute "minimum_hours"
     */
    public function testPropertyMinimumHours()
    {

    }

    /**
     * Test attribute "mobile_email"
     */
    public function testPropertyMobileEmail()
    {

    }

    /**
     * Test attribute "mobile_extension"
     */
    public function testPropertyMobileExtension()
    {

    }

    /**
     * Test attribute "mobile_phone"
     */
    public function testPropertyMobilePhone()
    {

    }

    /**
     * Test attribute "notes"
     */
    public function testPropertyNotes()
    {

    }

    /**
     * Test attribute "office_email"
     */
    public function testPropertyOfficeEmail()
    {

    }

    /**
     * Test attribute "office_extension"
     */
    public function testPropertyOfficeExtension()
    {

    }

    /**
     * Test attribute "office_phone"
     */
    public function testPropertyOfficePhone()
    {

    }

    /**
     * Test attribute "project_default_board"
     */
    public function testPropertyProjectDefaultBoard()
    {

    }

    /**
     * Test attribute "project_default_department_id"
     */
    public function testPropertyProjectDefaultDepartmentId()
    {

    }

    /**
     * Test attribute "project_default_location_id"
     */
    public function testPropertyProjectDefaultLocationId()
    {

    }

    /**
     * Test attribute "reports_to"
     */
    public function testPropertyReportsTo()
    {

    }

    /**
     * Test attribute "require_expense_entry_flag"
     */
    public function testPropertyRequireExpenseEntryFlag()
    {

    }

    /**
     * Test attribute "require_start_and_end_time_on_time_entry_flag"
     */
    public function testPropertyRequireStartAndEndTimeOnTimeEntryFlag()
    {

    }

    /**
     * Test attribute "require_time_sheet_entry_flag"
     */
    public function testPropertyRequireTimeSheetEntryFlag()
    {

    }

    /**
     * Test attribute "restrict_default_sales_territory_flag"
     */
    public function testPropertyRestrictDefaultSalesTerritoryFlag()
    {

    }

    /**
     * Test attribute "restrict_default_warehouse_bin_flag"
     */
    public function testPropertyRestrictDefaultWarehouseBinFlag()
    {

    }

    /**
     * Test attribute "restrict_default_warehouse_flag"
     */
    public function testPropertyRestrictDefaultWarehouseFlag()
    {

    }

    /**
     * Test attribute "restrict_department_flag"
     */
    public function testPropertyRestrictDepartmentFlag()
    {

    }

    /**
     * Test attribute "restrict_location_flag"
     */
    public function testPropertyRestrictLocationFlag()
    {

    }

    /**
     * Test attribute "restrict_project_default_department_flag"
     */
    public function testPropertyRestrictProjectDefaultDepartmentFlag()
    {

    }

    /**
     * Test attribute "restrict_project_default_location_flag"
     */
    public function testPropertyRestrictProjectDefaultLocationFlag()
    {

    }

    /**
     * Test attribute "restrict_schedule_flag"
     */
    public function testPropertyRestrictScheduleFlag()
    {

    }

    /**
     * Test attribute "restrict_service_default_department_flag"
     */
    public function testPropertyRestrictServiceDefaultDepartmentFlag()
    {

    }

    /**
     * Test attribute "restrict_service_default_location_flag"
     */
    public function testPropertyRestrictServiceDefaultLocationFlag()
    {

    }

    /**
     * Test attribute "sales_default_location_id"
     */
    public function testPropertySalesDefaultLocationId()
    {

    }

    /**
     * Test attribute "schedule_capacity"
     */
    public function testPropertyScheduleCapacity()
    {

    }

    /**
     * Test attribute "schedule_default_department_id"
     */
    public function testPropertyScheduleDefaultDepartmentId()
    {

    }

    /**
     * Test attribute "schedule_default_location_id"
     */
    public function testPropertyScheduleDefaultLocationId()
    {

    }

    /**
     * Test attribute "security_level"
     */
    public function testPropertySecurityLevel()
    {

    }

    /**
     * Test attribute "security_location_id"
     */
    public function testPropertySecurityLocationId()
    {

    }

    /**
     * Test attribute "security_role"
     */
    public function testPropertySecurityRole()
    {

    }

    /**
     * Test attribute "service_default_board"
     */
    public function testPropertyServiceDefaultBoard()
    {

    }

    /**
     * Test attribute "service_default_department_id"
     */
    public function testPropertyServiceDefaultDepartmentId()
    {

    }

    /**
     * Test attribute "service_default_location_id"
     */
    public function testPropertyServiceDefaultLocationId()
    {

    }

    /**
     * Test attribute "service_location"
     */
    public function testPropertyServiceLocation()
    {

    }

    /**
     * Test attribute "service_teams"
     */
    public function testPropertyServiceTeams()
    {

    }

    /**
     * Test attribute "time_approver"
     */
    public function testPropertyTimeApprover()
    {

    }

    /**
     * Test attribute "time_reminder_email_flag"
     */
    public function testPropertyTimeReminderEmailFlag()
    {

    }

    /**
     * Test attribute "time_sheet_start_date"
     */
    public function testPropertyTimeSheetStartDate()
    {

    }

    /**
     * Test attribute "time_zone"
     */
    public function testPropertyTimeZone()
    {

    }

    /**
     * Test attribute "title"
     */
    public function testPropertyTitle()
    {

    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {

    }

    /**
     * Test attribute "vendor_number"
     */
    public function testPropertyVendorNumber()
    {

    }

    /**
     * Test attribute "warehouse"
     */
    public function testPropertyWarehouse()
    {

    }

    /**
     * Test attribute "warehouse_bin"
     */
    public function testPropertyWarehouseBin()
    {

    }

    /**
     * Test attribute "work_role"
     */
    public function testPropertyWorkRole()
    {

    }

    /**
     * Test attribute "work_type"
     */
    public function testPropertyWorkType()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

    /**
     * Test attribute "system_flag"
     */
    public function testPropertySystemFlag()
    {

    }

}
