<?php
/**
 * MenuEntryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * MenuEntryTest Class Doc Comment
 *
 * @category    Class */
// * @description MenuEntry
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MenuEntryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MenuEntry"
     */
    public function testMenuEntry()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "menu_location"
     */
    public function testPropertyMenuLocation()
    {

    }

    /**
     * Test attribute "caption"
     */
    public function testPropertyCaption()
    {

    }

    /**
     * Test attribute "link"
     */
    public function testPropertyLink()
    {

    }

    /**
     * Test attribute "new_window_flag"
     */
    public function testPropertyNewWindowFlag()
    {

    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {

    }

    /**
     * Test attribute "origin"
     */
    public function testPropertyOrigin()
    {

    }

    /**
     * Test attribute "add_all_locations"
     */
    public function testPropertyAddAllLocations()
    {

    }

    /**
     * Test attribute "remove_all_locations"
     */
    public function testPropertyRemoveAllLocations()
    {

    }

    /**
     * Test attribute "small_menu_icon_id"
     */
    public function testPropertySmallMenuIconId()
    {

    }

    /**
     * Test attribute "large_menu_icon_id"
     */
    public function testPropertyLargeMenuIconId()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
