<?php
/**
 * UserDefinedFieldTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Spinen\ConnectWise\Clients\System;

/**
 * UserDefinedFieldTest Class Doc Comment
 *
 * @category    Class */
// * @description UserDefinedField
/**
 * @package     Spinen\ConnectWise\Clients\System
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserDefinedFieldTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "UserDefinedField"
     */
    public function testUserDefinedField()
    {

    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {

    }

    /**
     * Test attribute "pod_id"
     */
    public function testPropertyPodId()
    {

    }

    /**
     * Test attribute "caption"
     */
    public function testPropertyCaption()
    {

    }

    /**
     * Test attribute "sequence_number"
     */
    public function testPropertySequenceNumber()
    {

    }

    /**
     * Test attribute "help_text"
     */
    public function testPropertyHelpText()
    {

    }

    /**
     * Test attribute "field_type_identifier"
     */
    public function testPropertyFieldTypeIdentifier()
    {

    }

    /**
     * Test attribute "number_decimals"
     */
    public function testPropertyNumberDecimals()
    {

    }

    /**
     * Test attribute "entry_type_identifier"
     */
    public function testPropertyEntryTypeIdentifier()
    {

    }

    /**
     * Test attribute "required_flag"
     */
    public function testPropertyRequiredFlag()
    {

    }

    /**
     * Test attribute "display_on_screen_flag"
     */
    public function testPropertyDisplayOnScreenFlag()
    {

    }

    /**
     * Test attribute "read_only_flag"
     */
    public function testPropertyReadOnlyFlag()
    {

    }

    /**
     * Test attribute "list_view_flag"
     */
    public function testPropertyListViewFlag()
    {

    }

    /**
     * Test attribute "button_url"
     */
    public function testPropertyButtonUrl()
    {

    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {

    }

    /**
     * Test attribute "business_unit_ids"
     */
    public function testPropertyBusinessUnitIds()
    {

    }

    /**
     * Test attribute "location_ids"
     */
    public function testPropertyLocationIds()
    {

    }

    /**
     * Test attribute "add_all_business_units"
     */
    public function testPropertyAddAllBusinessUnits()
    {

    }

    /**
     * Test attribute "remove_all_business_units"
     */
    public function testPropertyRemoveAllBusinessUnits()
    {

    }

    /**
     * Test attribute "add_all_locations"
     */
    public function testPropertyAddAllLocations()
    {

    }

    /**
     * Test attribute "remove_all_locations"
     */
    public function testPropertyRemoveAllLocations()
    {

    }

    /**
     * Test attribute "date_created"
     */
    public function testPropertyDateCreated()
    {

    }

    /**
     * Test attribute "_info"
     */
    public function testPropertyInfo()
    {

    }

}
