<?php
/**
 * MenuEntriesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * System API
 *
 * ConnectWise System API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: platform@connectwise.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Spinen\ConnectWise\Clients\System;

use \Spinen\ConnectWise\Clients\System\Configuration;
use \Spinen\ConnectWise\Clients\System\ApiClient;
use \Spinen\ConnectWise\Clients\System\ApiException;
use \Spinen\ConnectWise\Clients\System\ObjectSerializer;

/**
 * MenuEntriesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Spinen\ConnectWise\Clients\System
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MenuEntriesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test case for systemMenuentriesCountGet
     *
     * .
     *
     */
    public function testSystemMenuentriesCountGet()
    {

    }

    /**
     * Test case for systemMenuentriesGet
     *
     * .
     *
     */
    public function testSystemMenuentriesGet()
    {

    }

    /**
     * Test case for systemMenuentriesIdDelete
     *
     * .
     *
     */
    public function testSystemMenuentriesIdDelete()
    {

    }

    /**
     * Test case for systemMenuentriesIdGet
     *
     * .
     *
     */
    public function testSystemMenuentriesIdGet()
    {

    }

    /**
     * Test case for systemMenuentriesIdImageGet
     *
     * .
     *
     */
    public function testSystemMenuentriesIdImageGet()
    {

    }

    /**
     * Test case for systemMenuentriesIdImagePost
     *
     * .
     *
     */
    public function testSystemMenuentriesIdImagePost()
    {

    }

    /**
     * Test case for systemMenuentriesIdPatch
     *
     * .
     *
     */
    public function testSystemMenuentriesIdPatch()
    {

    }

    /**
     * Test case for systemMenuentriesIdPut
     *
     * .
     *
     */
    public function testSystemMenuentriesIdPut()
    {

    }

    /**
     * Test case for systemMenuentriesPost
     *
     * .
     *
     */
    public function testSystemMenuentriesPost()
    {

    }

}
